### ISSUE TITLE
Palette selection for character models

### ISSUE THREAD

**Issue by PiKeyAr** [SonicFreak94/sadx-dc-lighting#11]
It appears that player models in the Dreamcast version use the third base palette (5) and the third specular (6) in most cases, however there are some exceptions. Tails' shoes and jumpball use specular 4 (8), same for most of E102 Gamma's body. There seems to be a correlation between the "ignore specular" material flag in character models and palette selection. In addition, certain parts of character models (Gamma's eyes etc.) have the "ignore lighting" flag, which makes them glow in the dark.

Therefore, base and specular palette selection for character models should be as follows:
Base palette: always use base 3 (5)
Ignore lighting on - not palettized
Ignore lighting off, ignore specular on - use specular 3 (6)
Ignore lighting off, ignore specular off - use specular 4 (8)

**Comment by PiKeyAr** [comment]
More information on palettes used by boss models.
Format: Boss - Base palette index (pair number), specular palette index (pair number).

Chaos0 - 1 (base 1), 4 (specular 2)
Chaos2 - 9 (base 5), 12 (specular 6)
Chaos4 - 1 (base 1), 4 (specular 2)
Chaos6 - 9 (base 5), 12 (specular 6)
Perfect Chaos (both parts) - 9 (base 5), 12 (specular 6), but Egg Carrier 2 and Eggmobile use 5 (base 3) and 8 (specular 4)
Egg Hornet - 1 (base 1), 4 (specular 2)
Egg Viper - 1 (base 1), 4 (specular 2)
Egg Walker - 1 (base 1), 4 (specular 2)
Zero, E-101MK2 - 1 (base 1), 4 (specular 2) and 2 (specular 1) for parts that ignore specular

**Comment by SonicFreak94** [comment]
I'm hoping to have at least the character palette selection done before release.

**Comment by SonicFreak94** [comment]
Added the character specular selection changes. Unfortunately though, SADX Sonic's materials seem to be weirdly configured, so his jump ball uses the wrong palette. This can be fixed, though.

**Comment by SonicFreak94** [comment]
Character materials have been corrected as of c0031beba7d5f366fedeb46cc457171e0d2e6fb6, so now all characters should have the correct palettes selected. Nothing on bosses yet.

**Comment by PiKeyAr** [comment]
A couple of things I overlooked:
Material 00012048 (Amy's hairband) should ignore specular, not ignore lighting.
Material 0011A080 (Big's belt buckle) should also ignore specular.
Looks accurate apart from these two.

**Comment by SonicFreak94** [comment]
Should be fixed in 2f9a67ab2f2a9b91227c190893647122b25f5064

**Comment by SonicFreak94** [comment]
Considering this fixed!

**Comment by SonicFreak94** [comment]
oops I broke it

**Comment by SonicFreak94** [comment]
I've just pushed a commit to help with the recent breaking of everything. Using the debug functions included in that commit, I can identify all instances where materials need to be updated based on patterns of texture IDs. By doing it this way, we can avoid setting values every frame that only realistically need to be set once.

That being said, let me know if it's closer to your original implementation now.

**Comment by PiKeyAr** [comment]
As of 1.0.21, it's a lot closer but there are still a few things:
1) Big's nose (matlist_0011BB58, material 0) - this should ignore specular.
2) Big's fishing rod (coil) without upgrades (0011E8E0 materials 0-2 and 0011E718, materials 0-1) should ignore specular.

**Comment by SonicFreak94** [comment]
Latest commit should address those issues.

Unless something else comes up, here's what needs to be done to consider this fixed:
- [ ] Update all those individual materials to use the proper arrays & de-dupe
- [ ] Specify which characters they're for (my fault, since they're missing the ___[character]_OBJECTS context)
- [ ] Fix Super Sonic's jump ball (and/or check the Dreamcast Super Sonic materials)

**Comment by SonicFreak94** [comment]
I guess this is fixed!

**Comment by PiKeyAr** [comment]
I noticed a few lighting differences while messing with the API, and they seem to affect the latest release version as well. I suggest reopening this.

Here's the test specular palette I was using (left is SA1, right is SADX):
![image](https://user-images.githubusercontent.com/23312549/27003176-c29feefa-4e2c-11e7-881a-32c4fdad8f18.png)

1. Amy's hairband - should use a higher specular index
![image](https://user-images.githubusercontent.com/23312549/27003182-d9d97fa0-4e2c-11e7-857e-04f8fbd52b8c.png)

2. Big (with upgrades) shoes and fishing rod use stage specular for some reason
![image](https://user-images.githubusercontent.com/23312549/27003183-dde83d02-4e2c-11e7-8276-cc5243a9c32e.png)

3. Gamma (with upgrades) Jet Booster and laser reticle should be using object specular, and the base of the reticle should use the level specular
![image](https://user-images.githubusercontent.com/23312549/27003185-e24f4b74-4e2c-11e7-9684-0953ca94e28e.png)

4. Gamma's chest is using object specular, while it should be using the second character specular
![image](https://user-images.githubusercontent.com/23312549/27003202-3d1d0dca-4e2d-11e7-921e-00c80c46bb61.png)

5. Big (no upgrades) belt buckle and shoes
![image](https://user-images.githubusercontent.com/23312549/27003203-40551d34-4e2d-11e7-96eb-74a69cf1ce35.png)

6. Gamma (no upgrades) trigger I guess. I'm not sure which specular it is, I guess we finally found a case where the last one or two palettes are used?
![image](https://user-images.githubusercontent.com/23312549/27003202-3d1d0dca-4e2d-11e7-921e-00c80c46bb61.png)

**Comment by PiKeyAr** [comment]
One more thing. When fighting Chaos 4, the moment it switches control to Sonic, the character's specular palette gets replaced with level specular. It only happens in Chaos 4 and only with Sonic, so this might be something the SADX does on purpose (it doesn't happen in SA1 though). This also occurs on pre-API builds of the PL mod.
I think the best way to avoid things like these is to hardcode palette indices for characters. Perhaps doing all characters using the API would work.

**Comment by PiKeyAr** [comment]
Here's a bunch of arrays and functions to fix character and boss materials using the API. This isn't meant to replace the FixCharacterMaterials thing, instead it can be integrated into it or if FixCharacterMaterials is rewritten to use the API they can be merged.
[materialfixes.txt](https://github.com/SonicFreak94/sadx-dc-lighting/files/1217149/materialfixes.txt)

**Comment by PiKeyAr** [comment]
`bool SpecialBossFunction(NJS_MATERIAL* material, Uint32 flags)
{
	set_diffuse(4, false);
	set_specular(5, false);
	use_default_diffuse(true);
	return true;
}`

`bool Chaos2Function(NJS_MATERIAL* material, Uint32 flags)
{
	if (CurrentLevel == 16)
	{
		set_diffuse(4, false);
		set_specular(5, false);
	}
	else
	{
		set_diffuse(2, false);
		set_specular(3, false);
	}
	use_default_diffuse(true);
	return true;
}`

**Comment by SonicFreak94** [comment]
👍
