### ISSUE TITLE
Palette selection for boss models

### ISSUE THREAD

**Issue by PiKeyAr** [SonicFreak94/sadx-dc-lighting#13]
Some boss models have specific base/specular palettes, which probably need to be dealt with on a case-by-case basis.

Format: Boss - Base palette index (pair number), specular palette index (pair number).
Individual palette indices are 1-based, base/specular indices are 0-based.

Chaos0 - 1 (base 0), 4 (specular 1)
Chaos2 - 9 (base 4), 12 (specular 5)
Chaos4 - 1 (base 0), 4 (specular 1)
Chaos6 - 9 (base 4), 12 (specular 5)
Perfect Chaos (both parts) - 9 (base 4), 12 (specular 5), but Egg Carrier 2 and Eggmobile use 5 (base 2) and 8 (specular 3)
Egg Hornet - 1 (base 0), 4 (specular 1)
Egg Viper - 1 (base 0), 4 (specular 1)
Egg Walker - 1 (base 0), 4 (specular 1)
E-101 - 1 (base 0), 4 (specular 1) with 2 (specular 0) for parts that ignore specular
Zero, E-101MK2 - 1 (base 0), 4 (specular 1) and 2 (specular 0) for parts that ignore specular

**Comment by SonicFreak94** [comment]
This turned out to be more complicated than I anticipated, so it's going to have to wait until after 1.0.

**Comment by PiKeyAr** [comment]
All bosses are now using correct palettes in the DC_Bosses mod. E-101MK2 has some weird stuff going on with its special effects that I don't know how to implement. There may be transparency issues involved.

Anyway I consider this done palette selection wise.
