### ISSUE TITLE
Custom texture transformation is not supported

### ISSUE THREAD

**Issue by PiKeyAr** [SonicFreak94/sadx-dc-lighting#14]
If an ingame object with environment mapping is hacked to have texture transformation, it won't display when palette lighting is on. Support for custom texture transformation is needed for the Dreamcast Final Egg mod, and will probably be needed in future Dreamcast mods.

**Comment by SonicFreak94** [comment]
b880e1e0a9ed3afef0649471d061f833d447db1d should address this issue. Let me know if it works.

**Comment by PiKeyAr** [comment]
Aww yea
