### ISSUE TITLE
Weird texture in Jungle section, Mystic Ruins

### ISSUE THREAD

**Issue by Sonikko** [SonicFreak94/sadx-dc-lighting#18]
Weird textures showing up in the Jungle section in Mystic Ruins.
![screenshot 2016-12-24 01 03 46](https://cloud.githubusercontent.com/assets/24740235/21464168/d8eb157c-c975-11e6-840c-5c2df8078d03.png)
![screenshot 2016-12-24 01 04 12](https://cloud.githubusercontent.com/assets/24740235/21464169/d8ecc9d0-c975-11e6-8c8f-57a50d1037aa.png)
![screenshot 2016-12-24 01 08 14](https://cloud.githubusercontent.com/assets/24740235/21464170/d8eefe94-c975-11e6-88c8-4e36047e9a06.png)
These are the mods I am using (Better SADX Core is just the adx mod plus AVA_TITLE_CMN.pvm and AVA_TITLE_CMN_SMALL.pvm)
![image](https://cloud.githubusercontent.com/assets/24740235/21464175/f3e3f7d6-c975-11e6-86a2-089f1bc0ddd2.png)

**Comment by Sonikko** [comment]
I found out a new update for the Modloader was out. It corrected these issues, sorry for pointing it out!

**Comment by SonicFreak94** [comment]
No problem. Otherwise a great quality report!
