### ISSUE TITLE
Sky Deck and Lost World lighting glitches

### ISSUE THREAD

**Issue by LimitCrown** [SonicFreak94/sadx-dc-lighting#21]
If you try to leave the Sky Deck stage when it has turned dark by going below the clouds, then the lighting will become messed up. If this is done from Trial Mode, then all of the characters will look dark. If any other stages are accessed after this, then the lighting of those stages will look dark as well. Going to the Sky Deck stage reverrts this. If Sky Deck was accessed from the Adventure Field and the stage is left when it is dark, then the Egg Carrier will look slightly washed out.

A similar thing can happen if you try to leave Lost World when Sonic is in the dark room with the mirrors. The lighting of the characters in the character select screen will look odd, but the lighting of the other stages won't be affected.

**Comment by SonicFreak94** [comment]
I have an idea of why this might be happening as far as Sky Deck is concerned. Its management object seemingly doesn't always get deleted, but the blend factor is reset in the destructor. I'm not sure about Lost World though; I'll need to test it out.

Thanks for the report!

**Comment by SonicFreak94** [comment]
It appears that the lighting bug in Lost World happens in vanilla SADX. In any case though, the Sky Deck bug has been fixed. Thanks again for the report!
