### ISSUE TITLE
Egg Viper explosion effect

### ISSUE THREAD

**Issue by PiKeyAr** [SonicFreak94/sadx-dc-lighting#26]
In SA1, when Egg Viper shoots an explosive beam, the walls fade to red as the explosion happens, and fade back to normal once it's over.
![red](https://cloud.githubusercontent.com/assets/23312549/21733595/bc39212a-d4a2-11e6-9a34-242b551de67a.png)
After Egg Viper is defeated and the vessel starts spinning around, the walls fade between a slight red tint and a full red tint continuously. When Egg Viper explodes at the end, the fade stops at a full red tint.
![red2](https://cloud.githubusercontent.com/assets/23312549/21733646/f2c0419c-d4a2-11e6-97e9-12a17a965747.png)
There are some weird colors in PL_M0B.BIN's Base 4 and Specular 4 (0-based) that could be related to this. Interestingly the walls in the Egg Viper landtable are set to ignore specular.

**Comment by PiKeyAr** [comment]
Looks like SADX has some leftover (?) code for this effect. There is a 4-byte value at 3C6E1EC that becomes 1 for the duration of the effect. sub_581960 calculates some values for it and sub_57E590 changes diffuse color and light direction. And of course it's not working in SADX for whatever reason.
If this functionality is too difficult to restore, perhaps it could be implemented in a way similar to the fire in Past cutscenes, though this time instead of having a separate palette it will be a red overlay with a different opacity over the existing palette.

The effect works like this:
- When Egg Viper is hit: a brief flash to full red and back to normal.
- When Egg Viper fires an explosive beam: fade to full red when the explosion is created, and fade to normal once it's over.
- When Egg Viper is defeated and the vessel starts spinning around, fade between a slight red tint and a full red tint continuously. 
- When Egg Viper explodes at the end, fade to a full red tint.

**Comment by PiKeyAr** [comment]
[I've recorded a video of the Egg Viper effect with test palettes](https://www.dropbox.com/s/z52ii0suwliwk5o/eggviper.mp4?dl=0). There seems to be a lot of stuff going on that I don't really understand.

**Comment by SonicFreak94** [comment]
That's really interesting. The interpolation infrastructure can probably facilitate that, but it's a matter of implementing the backend code.

**Comment by PiKeyAr** [comment]
I'm going to do this thing using the API so I'm closing this for now.
