### ISSUE TITLE
lightning shield graphical glitch

### ISSUE THREAD

**Issue by Thesch28** [SonicFreak94/sadx-dc-lighting#31]
When I use this mod I get a weird glitch with the lightning shield in some levels I have only seen this on Sky Deck and Lost World Here's a picture. http://oi65.tinypic.com/otoghw.jpg
those white boxes are moving all around the shield like if some textures of the shield got white or something sometimes I even seen them in yellow maybe this has something to do with stages with many lighting or fog effects because this glitch only happens on levels that have many effects like these 2.

**Comment by SonicFreak94** [comment]
Well, that makes 3 people who have had this bug so far. Unfortunately I'm completely unable to reproduce this on my system, so it probably won't be going away any time soon. Would you happen to be playing with an nvidia or intel GPU? I have an AMD GPU in my system, but the only other reports I've had are from systems with non-AMD GPUs.

In any case, I appreciate the report.

**Comment by Thesch28** [comment]
I so is more like a compatibility Issue with some GPUs. Other than that and some missing DC bosses effects (That have been reported already) the mods looks great.
If I see more glitches or things missing I'll make sure to report them.

**Comment by KNNSpeed** [comment]
Hi,

Same bug, same locations (it also happens in Final Egg, notably in the last tube Sonic runs down before you hit the switch that triggers the "Level 2 isolation wall opened" announcement). NVidia GT 750M here. 

It's extremely consistent in Lost World. Just grab a lightning shield and it will happen a lot beginning around the top of the cylindrical water room (the big room with the rising water, sea serpent, and the 3 switches) and into the mirror room. I actually can't get it to not happen.

Love your mods, btw. SADX almost feels like a whole new game!

**Comment by SonicFreak94** [comment]
Thanks for the detail. Having just tested it again though, I'm still unable to reproduce the issue, so I can't debug it myself.

For whoever is up to it, here's something to try: On [line 309](https://github.com/SonicFreak94/sadx-dc-lighting/blob/master/sadx-dc-lighting/lantern.fx#L309) of lantern.fx (in `sadx-dc-lighting/system/lantern.fx`), change `ps_fog` to `ps_nofog` and see if the issue persists. I'm honestly not sure that it's related since the colors don't match, though.

Other than that, the only thing that comes to mind is alpha checking, which can be disabled by commenting (or removing) [lines 279-282](https://github.com/SonicFreak94/sadx-dc-lighting/blob/master/sadx-dc-lighting/lantern.fx#L279-L282).

**Comment by KNNSpeed** [comment]
No difference. Though the overall framerate went down significantly when I commented out the alpha checking.

**Comment by Zetchzie** [comment]
So I finally have experienced the shield glitch myself I'm on AMD RX 480.

Strange thing is it only happens in certain areas. like it happens in skydeck ONLY in this area **so far**
![capture](https://cloud.githubusercontent.com/assets/15071652/24333540/b71086e4-1227-11e7-8a8c-4dc82c2a836d.PNG)

**Comment by SonicFreak94** [comment]
You're right, I can consistently reproduce it in Sky deck as well. Particularly when standing next to the falling spike balls and they spew out particles everywhere. Now let's see if I can actually fix it...

**Comment by SonicFreak94** [comment]
I've added a fix that appears to eliminate it on my system. If those affected could test [1.1.50-master](https://ci.appveyor.com/project/SonicFreak94/sadx-dc-lighting/build/1.1.50-master), it would be appreciated.

**Comment by cheatfreak47** [comment]
As I said on IRC, can confirm that fix worked for me. 👌

**Comment by LimitCrown** [comment]
The issue with the lightning shield is no longer present for me with this update.

**Comment by LighteningXL** [comment]
This used to happen to me in Sky Deck, Lost World, and Final Egg ever since v1.0.
With this patch? Not anymore… Problem is finally gone. Thank you!

**Comment by SonicFreak94** [comment]
Thanks for testing everyone! Finally fixed.
