### ISSUE TITLE
Playing a Game Gear game breaks palette lighting until the game is restarted

### ISSUE THREAD

**Issue by PiKeyAr** [SonicFreak94/sadx-dc-lighting#32]
(found by CheatFreak)

**Comment by SonicFreak94** [comment]
Well that's interesting to say the least. I'll have to look into it.

**Comment by SonicFreak94** [comment]
@cheatfreak47 I'm unable to reproduce this on master. If you could grab the latest master dev build from AppVeyor and confirm the issue, I would appreciate it. I suspect cd6db10f8fd5de585ecca354c2c7e590ce436764 may have fixed it. Having tested the build just before that however, I'm still unable to reproduce it. Maybe I'm missing a step?

**Comment by cheatfreak47** [comment]
I'll build the latest version and try it myself, the issue I encountered using the last release version, not the latest built from the source.

**Comment by SonicFreak94** [comment]
survey (irc) says: can't reproduce on master; closing for now
