### ISSUE TITLE
Game crashes when going into character select screen

### ISSUE THREAD

**Issue by LBPPlayer7** [SonicFreak94/sadx-dc-lighting#34]
The title explains everything. It only crashes on the character select screen, and nowhere else (I used level select in the TGS menus mod, and stages work fine)

**Comment by LBPPlayer7** [comment]
I almost instantly resolved the issue, it's an incompatibility with the Character Select Mod by MainMemory.

**Comment by MainMemory** [comment]
I thought I fixed that? Are you using the latest version of the Character Select Mod?

**Comment by LBPPlayer7** [comment]
I'm not sure.

**Comment by LBPPlayer7** [comment]
nope lol

**Comment by LBPPlayer7** [comment]
updating now

**Comment by MainMemory** [comment]
If everything's working now, you should close the issue.

**Comment by SonicFreak94** [comment]
I gotchu fam

**Comment by igdegoo** [comment]
> 
> 
> If everything's working now, you should close the issue.

ik this is 2 years old but i have this problem still
