### ISSUE TITLE
Chao Garden crash

### ISSUE THREAD

**Issue by PiKeyAr** [SonicFreak94/sadx-dc-lighting#37]
How to reproduce:
1. Start the game in Adventure Mode
2. Go to the Station Square garden
3. Teleport to the Mystic Ruins garden
4. Teleport to the Egg Carrier garden
5. Teleport back to the Station Square garden
6. Leave the garden

Unhandled exception at 0x0043A36B in sonic.exe: 0xC0000005: Access violation reading location 0x0F6E578C. Seems to be related to freeing landtable data.

The crash doesn't happen when the PL mod is disabled.

**Comment by SonicFreak94** [comment]
This appears to be a bug with the Mystic Ruins Chao Garden specifically. The exact cause is unknown, though, as the crash does in fact appear to be related to the landtable data. Very strange.

**Comment by Thesch28** [comment]
I actually had this issue but I didn't know if it was related to this mod also the game crashed after I played knuckles story for a long time and went to the Mystic Ruins Chao Garden. but most of the time the crash happened if I Teleported from Garden to Garden too much.
