### ISSUE TITLE
Knuckles Shovel Claws Missing Metallic lighting in SADX

### ISSUE THREAD

**Issue by Zetchzie** [SonicFreak94/sadx-dc-lighting#41]
So in the dreamcast version Knuckles shovel claws had a metallic shine to them that was scrapped in SADX i see that you've restored the Car lighting so is it possible to get the lighting back on the Shovel claws?

**Comment by SonicFreak94** [comment]
I haven't touched anything directly related to cars. In any case, this would be both a material and texture change which is outside the scope of this mod. We're working on getting character ports working through the mod loader, so once that's figured out, there will be a mod to resolve this.

**Comment by Zetchzie** [comment]
was it DC mods that gave the cars shine back? anyways thanks ^^

**Comment by PiKeyAr** [comment]
The shine is a material effect called environment mapping. You can see a similar effect on the Speed Highway helicopter, Station Square and Speed Highway 3 windows, Knuckles' shovel claws (SA1), the lion in the Casino etc. It was also applied to Super Sonic's model in the Dreamcast version. SADX has the effect intact on some objects, but for many objects/areas it was disabled.

Restoring this effect requires editing the material of the object. Ideally you would just replace the object's model with its Dreamcast counterpart. I can restore the Shovel Claws model when you see them for the first time, but changing them when they're part of Knuckles' character model probably requires editing CHRMODELS, which I'm not touching. I think these modifications have to wait until the character models are fully ported.

**Comment by Zetchzie** [comment]
all this stuff happening really excites me i just wish i could help i have no skills in coding but i do allot of picture editing but even that is amature level for me ^//^
