### ISSUE TITLE
Egg Carrier and Sky Deck Lighting Problem

### ISSUE THREAD

**Issue by supercoolsonic** [SonicFreak94/sadx-dc-lighting#44]
#### Encountered behavior
Sky Deck, when entered via Adventure Field as Knuckles, will cause the Egg Carrier to use that level's lighting upon exiting the level and returning to the Adventure Field.

No other mods or codes were used to trigger this, but I have triggered it before with the DC mods on, too. After that, entering the level from the Trial menu will give it its proper lighting. Entering it from the Adventure Field will carry over the Egg Carrier's lighting into Sky Deck.

#### Expected behavior
Each level should have its own lighting. The lighting of another level or area should not carry over to a completely separate level or area.

#### Installed mods

* sadx-input-mod
* sadx-dc-lighting
* None (Also got it with DC mods on)

No other mods on, Egg Carrier using Sky Deck lighting:
![lighting error](https://cloud.githubusercontent.com/assets/26051785/23447925/ada0d456-fe13-11e6-9afb-b1240d964b5d.png)

Trial Mode lighting (with DC mods on):
![trial mode to sky deck lighting](https://cloud.githubusercontent.com/assets/26051785/23447737/9109ff8a-fe12-11e6-8b09-49e451823d53.png)

Adventure Field lighting (with DC mods on):
![adventure field to sky deck lighting](https://cloud.githubusercontent.com/assets/26051785/23447741/996c29aa-fe12-11e6-9284-edf084fb9e31.png)

#### Steps to reproduce:

1. Start up the game, select Adventure Mod, and select Knuckles
2. Go to the the Egg Carrier. Note the lighting outside.
3. Enter Sky Deck from the Pool Room.
4. You can the exit the level whenever.
5. Upon returning, the Pool Room should have Sky Deck's lighting.
6. Exit the Pool Room, and with no other mods on, it should look like the first screenshot.
7. Trial Mode loads the correct lighting. Adventure Mode should fail every time after this, until the game is closed and opened again.

**Comment by SonicFreak94** [comment]
Would you mind verifying this with the latest dev build? You can get it from here: https://ci.appveyor.com/project/SonicFreak94/sadx-dc-lighting/build/artifacts

**Comment by supercoolsonic** [comment]
I tested it, using the same steps I stated to perform the issue with the currently released version of the mod, and the bug did not occur. I tested it with only the lighting mod on.

**Comment by SonicFreak94** [comment]
Cool, I guess I can consider this fixed then. Thanks for the report!
