### ISSUE TITLE
That "Shader creation failed with an unknown error. (Does blennder.fx exist?)" thing on the most recent dev build

### ISSUE THREAD

**Issue by Mumu03** [SonicFreak94/sadx-dc-lighting#47]
The latest dev build of this mod is not working for me. In fact, some error notification appeared in my face saying: "Shader creation failed with an unknown error. (Does blender.fx exist?)", then the game crashes. What's going on?

**Comment by SonicFreak94** [comment]
Note the branch suffix on the dev build version numbers (in this case, `1.1.*-depth-peel`). You can try it out if you really want to by pulling `blender.fx` from the depth-peel branch and putting it in  your SADX root directory, but it's entirely experimental and does not perform well by any stretch.

**Comment by Mumu03** [comment]
Gee, thanks! Where do i download blender.fx anyway?

**Comment by SonicFreak94** [comment]
On the main page for this repo above the list of files, there's a dropdown that says `master`. If you click on that and click `depth-peel`, you can find `blender.fx` in the `sadx-dc-lighting` directory. Click on it and then click the Raw button and you should be able to save the file from there.

**Comment by Mumu03** [comment]
Gee, thanks! Now i can test the Deth Peel versions at will!
