### ISSUE TITLE
Mod does not have Manifest

### ISSUE THREAD

**Issue by Zetchzie** [SonicFreak94/sadx-dc-lighting#48]
The Modloader update needs a manifest to complete updates

**Comment by SonicFreak94** [comment]
Manifests are added to release archives only.

**Comment by Zetchzie** [comment]
ah ok so should I just ignore the update

**Comment by LighteningXL** [comment]
Open mod.ini and remove the GitHubRepo string below to stop failed auto update.
GitHubRepo=sonicfreak94/sadx-dc-lightingGitHubAsset=sadx-dc-lighting.7z
