### ISSUE TITLE
Everything is black

### ISSUE THREAD

**Issue by MarioFreak2001** [SonicFreak94/sadx-dc-lighting#55]
I just can't seem to get this mod working.
I followed the instructions and I have the latest version of the mod, but everything is still black.
(also no picture because I couldn't get a screenshot)

**Comment by PiKeyAr** [comment]
What's your GPU model? Also are you able to see the SEGA screen or menus, or is the entire SADX screen always black?

**Comment by SonicFreak94** [comment]
If you could provide your GPU model and Windows version, I can look into the issue.

**Comment by MarioFreak2001** [comment]
I think this is it.
![ithinkthisistherightthing](https://user-images.githubusercontent.com/30168668/28215863-1549de6a-6875-11e7-8f95-eb9fde8c1653.png)
And I have Windows 7 Home Premium 32-bit.

@PiKeyAr I'm able to see the SEGA screen and menus, but everything that is a model is completely black aside from a few textures. (textures such as that blue bracelet thing that Sonic has that I forgot the name of, Big's eyes, and Sonic's spindash and jump dash effects)

**Comment by SonicFreak94** [comment]
The GeForce 6000 series cards appear to have only partial support for texture sampling in vertex shaders (which the lantern shader uses for vertex color selection). I'll investigate to see if there's a way to work around this without moving texture sampling to the pixel shader. Thanks for the report!

**Comment by MarioFreak2001** [comment]
How do I enable software vertex processing?

**Comment by SonicFreak94** [comment]
Could you try out [this build](https://ci.appveyor.com/project/SonicFreak94/sadx-dc-lighting/build/1.2.53-master/artifacts) and see if it resolves the issue?

**Comment by SonicFreak94** [comment]
(Paging @MarioFreak2001 !)

**Comment by SonicFreak94** [comment]
Seems to work for Shilz who also has this GPU. Considering fixed.

**Comment by MarioFreak2001** [comment]
This version presents a new problem.
The game just crashes every time I try to go to the character select screen.

**Comment by SonicFreak94** [comment]
Update d3d8to9.

**Comment by MarioFreak2001** [comment]
Thank you!
