### ISSUE TITLE
Game Crashes Before Character Select Screen

### ISSUE THREAD

**Issue by Thesch28** [SonicFreak94/sadx-dc-lighting#56]
So I downloaded the latest Version of the mod here: https://ci.appveyor.com/project/SonicFreak94/sadx-dc-lighting/build/artifacts
After installing it, i ran my game and it crashed everytime I tried to go to the character select for example Adventure Mode.

**Comment by SonicFreak94** [comment]
It looks like AppVeyor skipped commit 16795b9f492738cfbb8f33f0be94806593033a6c

It's crashing because I updated the d3d8to9 submodule to be compatible with the latest release version. Grab that from its repo (linked in README.md) and it should work fine.

**Comment by Thesch28** [comment]
sorry but I can't find the README.md

**Comment by Thesch28** [comment]
Now it works, thanks!
