### ISSUE TITLE
it only happen in combination with SA1_Chars mod made by ItsEasyActually

### ISSUE THREAD

**Issue by shadic2001** [SonicFreak94/sadx-dc-lighting#60]
#### Encountered behavior
Write a brief description of the bug you encountered here.

#### Expected behavior
Write a brief description of the behavior you expected here.

#### Installed mods

* sadx-input-mod
* sadx-dc-lighting
* ???

#### Steps to reproduce:

1. Steal Burger Shop statue
2. Place him in traffic
3. ???

**Comment by PiKeyAr** [comment]
Somebody set up us the bomb?
Please provide a proper description of the issue.

**Comment by RinMaru** [comment]
@PiKeyAr  you can close this its not a bug hes talking about the cars going through the statue but it happens with or without the mod

**Comment by SonicFreak94** [comment]
no
