### ISSUE TITLE
Allow loading PL/SL files from the mod's system folder without callbacks

### ISSUE THREAD

**Issue by PiKeyAr** [SonicFreak94/sadx-dc-lighting#64]
At the moment a callback is required for a mod to load custom PL/SL files. It works fine, but it would be easier for modders if the PL/SL files could be loaded directly from the mod's system folder, much like PVM replacements.

**Comment by SonicFreak94** [comment]
This requires mod loader functionality. I'm working on that and testing it in this project.

**Comment by SonicFreak94** [comment]
Fixed by efafe58905b5e4d8bc5fb29fb679180b16c98733
