### ISSUE TITLE
Add installation instructions to README.md

### ISSUE THREAD

**Issue by Stevoisiak** [SonicFreak94/sadx-dc-lighting#67]
Currently the README.md is a bit sparse on instructions. It should include a section with instructions for how to install the mod, and what the minimum requirements are. That way, if someone downloads the mod and goes to install it an hour later, they have the instructions for offline use.

You could use the installation instructions from the [Sonic Hacking Contest page](http://sonichacking.org/entry/19).

**Comment by RinMaru** [comment]
it doesnt really need instructions download DC Lighting and download dx8to9 then put the extracted folder (DC Lighting) into the mods folder and the dll in the game root then done

**Comment by RinMaru** [comment]
instructions aren't really needed :\

**Comment by cheatfreak47** [comment]
What someone should do is write a general Sonic Mod Loader documentation. Maybe I will do this sometime when I'm less lazy.

**Comment by PiKeyAr** [comment]
README.MD has been updated with installation instructions
