### ISSUE TITLE
Some Models Appear White

### ISSUE THREAD

**Issue by iiHATElosing** [SonicFreak94/sadx-dc-lighting#70]
I never played the original sonic adventure so this may not be an issue at all. so i was playing the casino level and i noticed that sonic was looking a little whiter than usual. i shrugged it off and kept playing, then i noticed in twinkle park it happens again. then i was watching the master emerald cutscene (where everything is on fire) and everything was red, i couldnt even see the green of the master emerald!

**Comment by cheatfreak47** [comment]
Can you please get screenshots?

**Comment by iiHATElosing** [comment]
![28053922_744947062376564_568956385_n](https://user-images.githubusercontent.com/36521439/36283733-5f84b240-1273-11e8-8512-5e828cc05bd8.png)

**Comment by cheatfreak47** [comment]
Yes, as I suspected, that is the correct look for the dc-lighting mod.
[Example of that stage on SA1 DC](https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Videos/Twinkle%20Park/thumbs/Start_DC.png)

**Comment by iiHATElosing** [comment]
no bug? to me it seems like one. especially when it came to the master emerald cutscene (which i cant show because im unable to go back to that cutscene)

**Comment by cheatfreak47** [comment]
@iiHATElosing The emerald altar is engulfed in a blazing fire, everything is reflective red and it's supposed to be tense, having a giant honking green glowy jewel would be pretty jarring no?

It's no bug, this is intended behavior. You're probably just used to how DX looks which is pretty ugly and crappy to be honest.

**Comment by iiHATElosing** [comment]
i never played the dx, i was just thinking that the glow of the master emerald would at least be slightly present, it looked like a black rock to me. i never played dx either, this is solely my very first time playing sonic adventure (well second but that was back in 1999 when i was 5 but i dont remember that well). i guess i only called it a bug because im not used to it. thanks for straightening this out
